//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoTrailsWebServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class trackpoint
    {
        public decimal id { get; set; }
        public long trail_id { get; set; }
        public int order { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public Nullable<short> elevation { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
    
        public virtual trail trail { get; set; }
    }
}
