//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoTrailsWebServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class trail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trail()
        {
            this.trackpoints = new HashSet<trackpoint>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<System.TimeSpan> duration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trackpoint> trackpoints { get; set; }
    }
}
