package phototrails.entity;
// Generated Oct 19, 2016 9:46:30 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Trackpoint generated by hbm2java
 */
@Entity
@Table(name="trackpoint"
    ,catalog="phototrails"
    , uniqueConstraints = @UniqueConstraint(columnNames={"trail", "order"}) 
)
@XmlRootElement
public class Trackpoint  implements java.io.Serializable {


     private Long id;
     private Trail trail;
     private short order;
     private BigDecimal latitude;
     private BigDecimal longitude;
     private Short elevation;
     private Date dateTime;

    public Trackpoint() {
    }

	
    public Trackpoint(Trail trail, short order, BigDecimal latitude, BigDecimal longitude) {
        this.trail = trail;
        this.order = order;
        this.latitude = latitude;
        this.longitude = longitude;
    }
    public Trackpoint(Trail trail, short order, BigDecimal latitude, BigDecimal longitude, Short elevation, Date dateTime) {
       this.trail = trail;
       this.order = order;
       this.latitude = latitude;
       this.longitude = longitude;
       this.elevation = elevation;
       this.dateTime = dateTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="trail", nullable=false)
    public Trail getTrail() {
        return this.trail;
    }
    
    public void setTrail(Trail trail) {
        this.trail = trail;
    }

    
    @Column(name="order", nullable=false)
    public short getOrder() {
        return this.order;
    }
    
    public void setOrder(short order) {
        this.order = order;
    }

    
    @Column(name="latitude", nullable=false, precision=8, scale=6)
    public BigDecimal getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="longitude", nullable=false, precision=9, scale=6)
    public BigDecimal getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    
    @Column(name="elevation")
    public Short getElevation() {
        return this.elevation;
    }
    
    public void setElevation(Short elevation) {
        this.elevation = elevation;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_time", length=19)
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }




}


