package phototrails.entity;
// Generated Oct 19, 2016 9:46:30 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Trail generated by hbm2java
 */
@Entity
@Table(name="trail"
    ,catalog="phototrails"
)
@XmlRootElement
public class Trail  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Date duration;
     private Set trackpoints = new HashSet(0);

    public Trail() {
    }

	
    public Trail(String name) {
        this.name = name;
    }
    public Trail(String name, String description, Date duration, Set trackpoints) {
       this.name = name;
       this.description = description;
       this.duration = duration;
       this.trackpoints = trackpoints;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="duration", length=8)
    public Date getDuration() {
        return this.duration;
    }
    
    public void setDuration(Date duration) {
        this.duration = duration;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="trail")
    public Set getTrackpoints() {
        return this.trackpoints;
    }
    
    public void setTrackpoints(Set trackpoints) {
        this.trackpoints = trackpoints;
    }




}


